Delete From params_des Where ENTIDAD = 'D_RPRTCLDDLTSTR0010';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','SHELL','/home/nae108834/CALIDAD_ALTAS_TRAFICADORAS/bin/SH_CALIDAD_ALTAS_TRAFICADORAS.sh','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','PARAM1_FECHA_EJECUCION','date_format(sysdate(),''%Y%m%d'')','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_RUTA','/home/nae108834/CALIDAD_ALTAS_TRAFICADORAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_PYTHON','calidad_altas_traficadoras.py','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','ESQUEMA','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','ESQUEMA_TMP','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','ETAPA','1','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_COLA_EJECUCION','capa_semantica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_NOMBRE_ARCH_1','Jefe_comercial.xlsx','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_NOMBRE_ARCH_2','Vendedores Movistar.xlsx','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_NOMBRE_ARCH_3','Captacion_Traf_Rec_Pre.csv','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_RUTA_HDFS_1','/documentos/otc_t_jefe_comercial_2','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_RUTA_HDFS_2','/documentos/otc_t_vendedores_2','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_MASTER','yarn','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_DRIVER_MEMORY','32G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_EXECUTOR_MEMORY','32G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_NUM_EXECUTORS','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_NUM_EXECUTORS_CORES','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_SFTP_RUTA_OUT','"/Share/comun/gestion&proyectos/INFORMACION~}<EXTERNA/Captacion_Pos_Pre"','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_RPRTCLDDLTSTR0010','VAL_SFTP_RUTA_IN','"/Share/VP~}<Ejecutiva/Ventas/Ventas~}<Indirectas/Planificacion~}<comercial/12.~}<VENDEDORES"','0','0');
Select * From params_des Where ENTIDAD = 'D_RPRTCLDDLTSTR0010';


sh -x /home/nae108834/CALIDAD_ALTAS_TRAFICADORAS/bin/SH_CALIDAD_ALTAS_TRAFICADORAS.sh 20231201
